# Jekyll config

title: Metro Ideas Lab
timezone: America/New_York
description: "We serve coffee, communities and city policy."
url:
# site.public boolean used to prevent preview sites from
# triggering unintended crawls and analytic counts.
# Change to `true` before pushing live site.
public: false

# Social media & contact
email: hello@metroideaslab.org
twitter: metroideaslab
facebook: metroideaslabpluscoffee
instagram: metroideaslab

# Build settings
include: 
- _pages
exclude:
- node_modules/
- bower_components/
- tmp/
- bower.json
- Gemfile*
- gulpfile.js
- gulp.config.js
- package.json
- README.md
- LICENSE
- npm-debug.log

# API
google_analytics: UA-68712194-3
